/**
 * Git 工作流演示的每一步状态。
 *
 * 三个区域：remote（GitHub）、local（本地 git 仓库）、disk（磁盘上的工作区）。
 * remote / local 各有 main、feature 两个分支槽位，disk 只显示当前检出的分支。
 * 每个提交用一个 id 表示，同一 id 在不同区域出现代表"同一个提交被复制过去了"。
 *
 * highlight：本步新增或变化的节点，格式 "区域.分支.提交id" 或 "区域.分支"（整行标签）。
 * arrows：跨区域传输箭头，从 from 区域的某个提交指向 to 区域的同列提交。
 */

export const COMMITS = {
  init: { label: "Init" },
  update: { label: "update" },
  c1: { label: "commit" },
  c1r: { label: "commit'" },
  update2: { label: "update2" },
  wip: { label: "修改中", dirty: true },
};

export const BRANCH_NAME = { main: "main", feature: "my-feature" };

export const STEPS = [
  {
    title: "初始状态",
    cmd: null,
    desc: "GitHub 上有一个仓库，主分支 main 只有一个提交 Init。本地什么都没有。",
    remote: { main: ["init"] },
    local: {},
    disk: null,
    head: null,
    highlight: [],
    arrows: [],
  },
  {
    title: "克隆仓库",
    cmd: "git clone https://github.com/example/example.git",
    desc: "把远端仓库完整复制到本地。此时远端、本地 git、磁盘三者完全一致。",
    remote: { main: ["init"] },
    local: { main: ["init"] },
    disk: { branch: "main", commits: ["init"] },
    head: "main",
    highlight: ["local.main", "local.main.init", "disk.main", "disk.main.init"],
    arrows: [
      { from: "remote", to: "local", branch: "main", col: 0 },
      { from: "local", to: "disk", branch: "main", col: 0 },
    ],
  },
  {
    title: "新建功能分支",
    cmd: "git checkout -b my-feature",
    desc: "从当前分支复制出 my-feature 并切换过去。两个分支现在指向同一个提交，磁盘内容没变。",
    remote: { main: ["init"] },
    local: { main: ["init"], feature: ["init"] },
    disk: { branch: "feature", commits: ["init"] },
    head: "feature",
    highlight: ["local.feature", "local.feature.init", "disk.feature"],
    arrows: [],
  },
  {
    title: "修改代码",
    cmd: "git diff",
    desc: "在编辑器里改文件，只有磁盘变了，git 还不知道。用 git diff 查看磁盘和 git 之间的差异。",
    remote: { main: ["init"] },
    local: { main: ["init"], feature: ["init"] },
    disk: { branch: "feature", commits: ["init", "wip"] },
    head: "feature",
    highlight: ["disk.feature.wip"],
    arrows: [],
  },
  {
    title: "提交到本地 git",
    cmd: "git add <changed_file> && git commit",
    desc: "add 把改动放进暂存区，commit 生成一个新提交。本地 my-feature 领先本地 main 一个提交，远端还一无所知。",
    remote: { main: ["init"] },
    local: { main: ["init"], feature: ["init", "c1"] },
    disk: { branch: "feature", commits: ["init", "c1"] },
    head: "feature",
    highlight: ["local.feature.c1", "disk.feature.c1"],
    arrows: [{ from: "disk", to: "local", branch: "feature", col: 1 }],
  },
  {
    title: "推送分支到远端",
    cmd: "git push origin my-feature",
    desc: "GitHub 上多出一个 my-feature 分支，保存着你的改动。",
    remote: { main: ["init"], feature: ["init", "c1"] },
    local: { main: ["init"], feature: ["init", "c1"] },
    disk: { branch: "feature", commits: ["init", "c1"] },
    head: "feature",
    highlight: ["remote.feature", "remote.feature.init", "remote.feature.c1"],
    arrows: [{ from: "local", to: "remote", branch: "feature", col: 1 }],
  },
  {
    title: "远端主分支有了新提交",
    cmd: null,
    desc: "你在开发的时候，别人往 main 推了一个 update。你的分支是基于旧的 Init 做的，需要同步。",
    remote: { main: ["init", "update"], feature: ["init", "c1"] },
    local: { main: ["init"], feature: ["init", "c1"] },
    disk: { branch: "feature", commits: ["init", "c1"] },
    head: "feature",
    highlight: ["remote.main.update"],
    arrows: [],
  },
  {
    title: "切回主分支",
    cmd: "git checkout main",
    desc: "磁盘上的文件回到 main 的状态，也就是 Init。你的修改还在本地 git 的 my-feature 里，没有丢。",
    remote: { main: ["init", "update"], feature: ["init", "c1"] },
    local: { main: ["init"], feature: ["init", "c1"] },
    disk: { branch: "main", commits: ["init"] },
    head: "main",
    highlight: ["disk.main", "local.main"],
    arrows: [],
  },
  {
    title: "拉取远端主分支",
    cmd: "git pull origin main",
    desc: "远端的 update 同步到本地 main 和磁盘。现在本地 main 和远端 main 一致。",
    remote: { main: ["init", "update"], feature: ["init", "c1"] },
    local: { main: ["init", "update"], feature: ["init", "c1"] },
    disk: { branch: "main", commits: ["init", "update"] },
    head: "main",
    highlight: ["local.main.update", "disk.main.update"],
    arrows: [
      { from: "remote", to: "local", branch: "main", col: 1 },
      { from: "local", to: "disk", branch: "main", col: 1 },
    ],
  },
  {
    title: "切回功能分支",
    cmd: "git checkout my-feature",
    desc: "磁盘回到你的修改。但 my-feature 还是基于 Init，不包含 update。",
    remote: { main: ["init", "update"], feature: ["init", "c1"] },
    local: { main: ["init", "update"], feature: ["init", "c1"] },
    disk: { branch: "feature", commits: ["init", "c1"] },
    head: "feature",
    highlight: ["disk.feature", "local.feature"],
    arrows: [],
  },
  {
    title: "变基到最新主分支",
    cmd: "git rebase main",
    desc: "先把你的提交拿开，接上 main 的 update，再把你的提交重放到后面。内容一样但提交号变了，所以写成 commit'。有冲突就在这一步手动解决。",
    remote: { main: ["init", "update"], feature: ["init", "c1"] },
    local: { main: ["init", "update"], feature: ["init", "update", "c1r"] },
    disk: { branch: "feature", commits: ["init", "update", "c1r"] },
    head: "feature",
    highlight: ["local.feature.update", "local.feature.c1r", "disk.feature.update", "disk.feature.c1r"],
    arrows: [],
  },
  {
    title: "强制推送",
    cmd: "git push -f origin my-feature",
    desc: "rebase 改写了历史，远端的 my-feature 和本地对不上，必须加 -f 覆盖。",
    remote: { main: ["init", "update"], feature: ["init", "update", "c1r"] },
    local: { main: ["init", "update"], feature: ["init", "update", "c1r"] },
    disk: { branch: "feature", commits: ["init", "update", "c1r"] },
    head: "feature",
    highlight: ["remote.feature.update", "remote.feature.c1r"],
    arrows: [{ from: "local", to: "remote", branch: "feature", col: 2 }],
  },
  {
    title: "提 PR，Squash and merge",
    cmd: "GitHub：Pull Request → Squash and merge → Delete branch",
    desc: "维护者审查后把 my-feature 的所有提交压成一个 update2 放进 main，然后删掉远端的 my-feature。",
    remote: { main: ["init", "update", "update2"] },
    local: { main: ["init", "update"], feature: ["init", "update", "c1r"] },
    disk: { branch: "feature", commits: ["init", "update", "c1r"] },
    head: "feature",
    highlight: ["remote.main.update2"],
    arrows: [],
  },
  {
    title: "删除本地分支",
    cmd: "git checkout main && git branch -D my-feature",
    desc: "远端分支删了，本地的还在。切回 main 后删掉本地 my-feature。",
    remote: { main: ["init", "update", "update2"] },
    local: { main: ["init", "update"] },
    disk: { branch: "main", commits: ["init", "update"] },
    head: "main",
    highlight: ["disk.main", "local.main"],
    arrows: [],
  },
  {
    title: "同步主分支",
    cmd: "git pull origin main",
    desc: "拉取最新的 main。远端、本地、磁盘再次一致，回到和克隆之后一样的干净状态，下一个功能从这里开始。",
    remote: { main: ["init", "update", "update2"] },
    local: { main: ["init", "update", "update2"] },
    disk: { branch: "main", commits: ["init", "update", "update2"] },
    head: "main",
    highlight: ["local.main.update2", "disk.main.update2"],
    arrows: [
      { from: "remote", to: "local", branch: "main", col: 2 },
      { from: "local", to: "disk", branch: "main", col: 2 },
    ],
  },
];
